version: "3.9"
services:
  rstudio:
    image: "rkrispin/flex_dash_env:dev.0.0.0.9000" 
    ports:
      - "8787:8787"
    volumes:
      - type: "bind"
        source: "C:\Users\Asus\Desktop\dash"
        target: "/home/rstudio"
      - type: "bind"
        source: "C:/Users/Asus/AppData/Roaming/RStudio"
        target: "/home/rstudio/.config/rstudio"
