---
title: "Shark Tank India Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: sketchy
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(flexdashboard) # for building dashboards
library(tidyverse) #for data manipulation
library(highcharter) # interactive visualization
```

```{r read}
shark <- read_csv("https://raw.githubusercontent.com/amrrs/sharktankindia-analysis/main/ShartankIndiaAllPitches.csv")
```

```{r summary}
min_investment <- min(shark[shark$`Investment Amount`>0,]$`Investment Amount`)
max_investment <- max(shark$`Investment Amount`)
avg_investment <- round(mean(shark$`Investment Amount`))
```


Row
-----------------------------------------------------------------------

### Min. Invest. (in Crores)

```{r}
valueBox(min_investment, icon = "fa-rupee-sign")
```

### Max. Invest. (in Crores)

```{r}
valueBox(max_investment, icon = "fa-rupee-sign")
```

### Avg. Invest. (in Crores)

```{r}
valueBox(avg_investment, 
         icon = "fa-rupee-sign")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Distribution of Investment Amount

```{r}
hchart(density(shark$`Investment Amount`), type = "area", color = "#B71C1C", name = "Investment Amount")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Top Invested Brands

```{r}
shark %>% 
  group_by(Brand) %>% 
  summarize(total_investment = sum(`Investment Amount`)) %>%
  arrange(desc(total_investment)) %>% 
  head(20) %>% 
  hchart("column", hcaes(x = Brand, y = total_investment))
```


### Top Invested Ideas

```{r}
shark %>% 
  group_by(Idea) %>% 
  summarize(total_investment = sum(`Investment Amount`)) %>%
  arrange(desc(total_investment)) %>% 
  head(20) %>% 
  hchart("column", hcaes(x = Idea, y = total_investment), color = "#ff0011")
```

