name: github action secret

on:
  push:
    branches: [ main ]
    
job:
  gethub-secret-action:
   runs-on: windows-lates
   
   steps:
   
    - name: Step 1 - Echo out a Github Actions Secret to the logs
     run: |
       echo "The Github Actions Secret will be masked: "
       echo ${{ secret.CANDY_SHOP }}
