name: github action secret

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: refresh the dashboard
    runs-on: ubuntu-22.04
    container: 
     image: rkrispin/flex_dash_env:dev.0.0.0.9000
    steps:
        uses: actions/checkout@v2
        with: 
          repo-token: ${{ secrets.CANDY_SHOP }}
         - name: Render Rmarkdown
        run: bash ./bash/data_refresh.sh "AhmedAlmustfa" "ahmedkhatir22@gmail.com"
