name: Pull request labeler
on: 
  schedule:
    - cron:  '0 */1 * * *'

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.CANDY_SHOP }}
